[tool.poetry]
name = "mazegen-sehallil"
version = "1.0.0"
description = "A modern terminal maze generator with reusable logic"
authors = ["sehallil <your.email@example.com>"]
readme = "README.md"

packages = [
    { include = "mazegen" },
    { include = "app" }
]

include = [
    { path = "config.txt", format = ["sdist", "wheel"] }
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
mazegen = "app.a_maze_ing:main_wrapper"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"